version: '3.8'

services:
  logistics-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: logistics-tracker
    ports:
      - "9091:9091"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tracking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sughosh@Cb#1234

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tracking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sughosh@Cb#1234
